
function action_give_task()
     local task = CGameTask()
     
     task:load("task_3")
     
     db.actor:give_task(task,1000*6000, false)
end
function _action_give_task()
     local task = CGameTask()
     
     task:load("artefact")
     task:set_title("artefact")
     
     local objective = SGameTaskObjective(task,1)
     objective:set_description("artefact_name")
     task:add_objective(objective)

     objective = SGameTaskObjective(task,2)
     objective:set_description("artefact_return")
     task:add_objective(objective)
     
     db.actor:give_task(task,1000*20, false)
end

function main111()
	local c = get_console()
	c:execute("disconnect")
end

function aaa_main()
 -- game.start_tutorial("part_1_pda")
	local o = level.debug_object("level_prefix_inventory_box")
	
 	o:set_tip_text("hello world")
--	o:set_tip_text_default("default hello world")
	o:set_nonscript_usable(true)

end


--run_string alife():create("wpn_binoc", db.actor:position(), db.actor:level_vertex_id(),db.actor:game_vertex_id())


function main________________()
	db.actor:give_game_news(game.translate_string("pass_to_2nd_door"), "ui\\ui_icons_task", Frect():set(0,100,50,50) ,0, 0)	
--	db.actor:give_talk_message("trader", "ui\\ui_icons_task",Frect():set(300,100,50,50),"iconed_trade_info")
--	db.actor:give_talk_message("Превед", "trader", "ui\\ui_icons_task",Frect():set(300,100,50,50),"iconed_trade_info")
--	db.actor:give_talk_message("Превед", "trader", "trader", "ui\\ui_icons_task",Frect():set(300,100,50,50),"iconed_trade_info")
--	db.actor:give_game_news("превед", "ui\\ui_icons_task", Frect():set(300,100,50,50),0,0)
--	db.actor:give_game_news("превед","trader", "ui\\ui_icons_task", Frect():set(300,100,50,50),0,0)
--	db.actor:give_game_news("trader","trader","trader", "ui\\ui_icons_task", Frect():set(300,100,50,50),0,0)
end


function _main()
	local radius = 30
	local ang    = 45
	local dir    = vector_rotate_y( db.actor:direction(), ang )
	level.spawn_phantom(db.actor:position():add( dir:mul(radius) ))
end

function ___main()
	action_give_task()
--	local info = "test_andy_info" 
--	db.actor:give_info_portion(info) 
--	alife():create("wpn_binoc", db.actor:position(), db.actor:level_vertex_id(),db.actor:game_vertex_id())		
	

--    alife():create ("wpn_knife", db.actor:position (), db.actor:level_vertex_id (),db.actor:game_vertex_id (), db.actor:id())


--	level.add_complex_effector("effector_radar_stop", 12345)
	
--	db.actor:activate_slot(db.actor:active_slot()+1)

--	local news_text = "%c[255,160,160,160]" .. "Задание выполнено" .. "\\n" .. "%c[default]" .. "Информация о винтовке FN-2000 а также куча всякой лабуды типа убить долбаного стрелка или помочь сраному раненому"

--	db.actor:give_game_news(news_text, "ui\\ui_pop_up_active_back", Frect():set(0,0,16,16), 0, 0)
--	local news_text = "%c[255,160,160,160]" .. "Задание выполнено" .. "\\n" .. "%c[default]" .. "Информация о винтовке FN-2000 а также куча всякой лабуды типа убить долбаного стрелка или помочь сраному раненому"
--	local a,b = get_task_info("ui_iconsTotalSmall_found","_money")
--	b:set(83,0,49,26)
--	db.actor:give_game_news(news_text, a, b, 0, 0)

--	db.actor:give_talk_message(news_text, "ui\\ui_icons_task",Frect():set(300,100,50,50),"iconed_trade_info")

-- game.start_tutorial("credits_seq")
	
	
	info = "tutorial_artefact_start" 
	db.actor:give_info_portion(info) 
	
	
--	info = "encyclopedy_weapons_wpn_groza" 
--	db.actor:give_info_portion(info) 
	
--	info = "encyclopedy_weapons_wpn_fn2000"
--	db.actor:give_info_portion(info) 

--	info = "encyclopedy_mutant_flesh"
--	db.actor:give_info_portion(info) 

--	info = "encyclopedy_zone_artifact_af-cristall-flower"
--	db.actor:give_info_portion(info) 
end

function wwwww_main()
	game.start_tutorial("part_1_pda")
end

function main()
   local h 		= hit()
   h.power 		= 0.05
   h.direction 	= vector():set(0, 0, 1)
   h.impulse 	= 0
   h.draftsman 	= db.actor
   h.type 		= hit.wound
   db.actor:hit(h)

--burn  		1
--shock  		1
--strike  		1
--wound  		1
--fire_wound  	1
--radiation   	1
--telepatic   	1
--chemical_burn 1
--explosion


end

function __main()
	local task = CGameTask()

	task:load("artefact")
	task:set_title("artefact_trader artefact_trader")
	local o0		= task:get_objective(0)
	o0:set_article_id("tm_artefact_test")
	
	local objective = SGameTaskObjective(task,1)
	objective:set_description("artefact_trader")
	task:add_objective(objective)

	objective = SGameTaskObjective(task,2)
	objective:set_description("artefact_trader_return")

	local time = 1*60*60*1000
	db.actor:give_task(task,time,false)

	--'

	task = CGameTask()

	task:load("artefact")
	task:set_title("artefact_trader artefact_trader")
	o0			= task:get_objective(0)
	o0:set_article_id("tm_artefact_test2")
	
	objective = SGameTaskObjective(task,1)
	objective:set_description("artefact_trader")
	task:add_objective(objective)

	objective = SGameTaskObjective(task,2)
	objective:set_description("artefact_trader_return")

	local time = 1*60*60*1000
	db.actor:give_task(task,time,false)
end
