-----------------------------------------------------------------------------------
-- Test Definitions
-----------------------------------------------------------------------------------
local object_list		= {}

object_list["test1"] = {
	"test1_dog1",
	"test1_dog2",
	"test1_dog3",
	"test1_dog4",
	"test1_dog5",
	"test1_dog6",
	"test1_dog7",
	"test1_dog8"
}

object_list["test2"] = {
	"test2_controller1"
}

object_list["test3"] = {
	"test3_controller1",
	"test3_flesh1",
	"test3_dog1",
	"test3_boar1"
}

object_list["test4"] = {
	"test4_dog1",
	"test4_dog2",
	"test4_dog3",
	"test4_dog4",
	"test4_dog5",
	"test4_dog6",
	"test4_dog7"
}

object_list["test5"] = {
	"test5_gigant1"
}

object_list["test6"] = {
	"test6_gigant1",
	"test6_gigant2"
}


------------------------------------------------------------------------------
-- Base Run function (load extern)
------------------------------------------------------------------------------
function r(index)
	test_utils.setup_test(object_list, nil)
	test_utils.run_test(index)
end

------------------------------------------------------------------------------
-- Main function (called on level load)
------------------------------------------------------------------------------
function main()
	test_utils.setup_test(object_list, nil)
	test_utils.run_global()
end
