function set_switch_online(story_id,value)
	alife():set_switch_online(alife():story_object(story_id):id(),value)
end

function set_switch_offline(story_id,value)
	alife():set_switch_offline(alife():story_object(story_id):id(),value)
end

function set_interactive(story_id,value)
	alife():set_interactive(alife():story_object(story_id):id(),value)
end

function object_online(object_id)
	return (alife() == nil) or alife():object(object_id).online
end
