----------------------------------------------------------------------------------------------------
-- Mob Home
----------------------------------------------------------------------------------------------------
-- Разработчик: Jim
----------------------------------------------------------------------------------------------------

local def_min_radius = 20
local def_max_radius = 40

class "mob_home"

----------------------------------------------------------------------------------------------------
-- CONSTRUCTION SCHEME
----------------------------------------------------------------------------------------------------
function mob_home:__init(obj, storage)
	self.object = obj
	self.st		= storage
end

----------------------------------------------------------------------------------------------------
-- RESET SCHEME
----------------------------------------------------------------------------------------------------
function mob_home:reset_scheme()
--[[
Добавлено: Haron
Описание: Теперь можно задавать радиусы home_min_radius и home_max_radius во флагах
          пути path_home. Для этого введены флаги minr, maxr. Они должны быть
          прописаны в первой точке пути. У радиусов заданых в секции приоритет
          больший чем для тех что заданы во флагах, т.е. если задано и там и там, то
          берутся значения из секции (сделано для обратной совместимости).
--]]
    local minr, maxr = def_min_radius, def_max_radius
	local ptr = patrol(self.st.home)
	local path_info = utils.parse_waypoint_data(self.st.home, ptr:flags(0), ptr:name(0))				
    local r = 0

    if self.st.home_min_radius then
        minr = self.st.home_min_radius
    else
        r = path_info.minr
        if r then
            r = tonumber(r)
            if r then
                minr = r
            end
        end
    end
    
    if self.st.home_max_radius then
        maxr = self.st.home_max_radius
    else
        r = path_info.maxr
        if r then
            r = tonumber(r)
            if r then
                maxr = r
            end
        end
    end

	-- check min and max radius
	if	minr > maxr then
		_G.abort("Mob_Home : Home Min Radius MUST be < Max Radius. Got: min radius = %d, max radius = %d.", minr, maxr)
	end 

	self.object:set_home(self.st.home, minr, maxr, self.st.aggressive)
end

----------------------------------------------------------------------------------------------------
-- UPDATE
----------------------------------------------------------------------------------------------------

function mob_home:update(delta)
	if xr_logic.try_switch_to_another_section(self.object, self.st, db.actor) then
		return
	end
end

function mob_home:deactivate()
	self.object:remove_home()
end

----------------------------------------------------------------------------------------------------
-- ADD_TO_BINDER
----------------------------------------------------------------------------------------------------
function add_to_binder(npc, ini, scheme, section, storage)
	printf("DEBUG: add_to_binder: npc:name()='%s', scheme='%s', section='%s'", npc:name(), scheme, section)

	local new_action = mob_home(npc, storage)

	-- Зарегистрировать все actions, в которых должен быть вызван метод reset_scheme при изменении настроек схемы:
	xr_logic.subscribe_action_for_events(npc, storage, new_action)
end

----------------------------------------------------------------------------------------------------
-- SET_SCHEME
----------------------------------------------------------------------------------------------------
function set_scheme(npc, ini, scheme, section, gulag_name)
	local storage				= xr_logic.assign_storage_and_bind(npc, ini, scheme, section)

	storage.logic				= xr_logic.cfg_get_switch_conditions(ini, section, npc)
	
	storage.home				= utils.cfg_get_string(ini, section, "path_home",			npc, true, gulag_name)
	storage.home_min_radius		= utils.cfg_get_number(ini, section, "home_min_radius",		npc, false) --, 20)
	storage.home_max_radius		= utils.cfg_get_number(ini, section, "home_max_radius",		npc, false) --, 40)
	
	storage.aggressive			= ini:line_exist( section, "aggressive_home")
end

