----------------------------------------------------------------------------------------------------
-- Mob panic threshold control
----------------------------------------------------------------------------------------------------
-- Разработчик: Чугай Александр
----------------------------------------------------------------------------------------------------

function reset_panic( npc, scheme, st, section )
	local panic_threshold = utils.cfg_get_number( st.ini, section, "panic", npc, false, nil )

	if panic_threshold then
		npc:set_custom_panic_threshold	(panic_threshold)
	else 
		npc:set_default_panic_threshold	()
	end
	
end

---------------------------------------------------------------------------------------------------------------------
function add_to_binder( npc, ini, scheme, section, storage )
end

function set_scheme( npc, ini, scheme, section, gulag_name )
	local st = xr_logic.assign_storage_and_bind( npc, ini, scheme, section )   	
	st.logic = xr_logic.cfg_get_switch_conditions( ini, section, npc )
end