function main()
	quest_agroprom.main()
	
	db.actor:give_info_portion("agroprom_military_case_have")
	db.actor:give_info_portion("agr_krot_band_done")
	db.actor:give_info_portion("agr_find_gunslinger_cache_start")
	db.actor:give_info_portion("agr_krot_secret_info")
	db.actor:give_info_portion("agr_find_gunslinger_cache_found")
	db.actor:give_info_portion("agr_find_gunslinger_cache_done")
	db.actor:give_info_portion("agroprom_find_stalker_phantom")	
end