function main1()
	local dog = m_monster_ai.m_MonsterBobik("dog", this.script_name(), "way")

    while(dog:execute()) do
    	wait()
    end

    dog:finalize()
end

function main()
	local dog = get_level_object("dog")
    dog:script(true, this.script_name())

    local pos1 = dog:level_vertex_id()

    while(true) do
    	if(dog:action() == nil) then
        	action(dog, move(move.walk_fwd, new_point(pos1, dog:level_vertex_id(), 8, 10), 1.5 ), cond( cond.move_end) )
        end

        wait()
    end

end
