local ini = ini_file("test_script.ltx")
printf	("%s",ini:r_string("test1","test2"))

local tokens = token_list()
tokens:add("enemy",		0)
tokens:add("neutral",	1)
tokens:add("friend",	2)

printf	("%d",ini:r_token("test1","token",tokens))

self.object:spawn_ini():

			.def("section_exist",	&CScriptIniFile::section_exist	)
			.def("line_exist",		&CScriptIniFile::line_exist		)
			.def("r_clsid",			&CScriptIniFile::r_clsid		)
			.def("r_bool",			&CScriptIniFile::r_bool			)
			.def("r_token",			&CScriptIniFile::r_token		)
			.def("r_string",		(LPCSTR (CScriptIniFile::*)	(LPCSTR, LPCSTR))(CScriptIniFile::r_string))
			.def("r_u32",			(u32	(CScriptIniFile::*)	(LPCSTR, LPCSTR))(CScriptIniFile::r_u32))
			.def("r_s32",			(int	(CScriptIniFile::*)	(LPCSTR, LPCSTR))(CScriptIniFile::r_s32))
			.def("r_float",			(float	(CScriptIniFile::*)	(LPCSTR, LPCSTR))(CScriptIniFile::r_float))
			.def("r_vector",		(Fvector(CScriptIniFile::*)	(LPCSTR, LPCSTR))(CScriptIniFile::r_fvector3))
			.def("line_count",		(u32	(CScriptIniFile::*)	(LPCSTR))		 (CScriptIniFile::line_count))
