-----------------------------------------------------------------------------------
-- Test Definitions
-----------------------------------------------------------------------------------
local object_list		= {}
local smart_terrains	= {}

-----------------------------------------------------------------------------------------
-- TEST 1
-----------------------------------------------------------------------------------------
object_list["test1"] = {
"yan_home_snork_01",
"yan_home_snork_0001",
"yan_home_snork_0000",
"yan_home_snork_0002",
"yan_home_snork_0003",
"yan_home_snork_0005",
"yan_home_snork_0006",
"yan_home_snork_0007",
"yan_home_snork_0008",
"yan_home_snork_0009",
"factory_m_snork_e",
"factory_m_snork_e_0000",
"factory_m_snork_e_0001",
"factory_m_snork_e_0002",
"factory_m_snork_e_0003",
"factory_m_snork_e_0004",
"factory_m_snork_e_0005",
"factory_m_snork_e_0006",
"factory_m_snork_e_0007",
"factory_m_snork_e_0008",
"factory_m_snork_e_0009",
"factory_m_snork_e_0010",
"factory_m_snork_e_0011",
"factory_m_snork_e_0012",
"factory_m_snork_e_0013",
"yan_home_snork_0010",
"yan_home_snork_0011",
"yan_home_snork_0012",
"yan_home_snork_0013",
"yan_home_snork_0014",
"yan_home_snork_0015",
"yan_home_snork_0016",
"yan_home_snork_0017",
"yan_home_snork_0018",
"yan_jump_snork_03",
"yan_jump_snork_02",
"yan_jump_snork_0000",
"yan_jump_snork_0001",
"yan_jump_snork_0002",
"yan_jump_snork_0003",
"yan_jump_snork_0004",
"yan_jump_snork_0005",
"yan_jump_snork_0006",
"yan_jump_snork_0007",
"yan_jump_snork_0008",
"yan_jump_snork_0009",
"yan_jump_snork_0010",
"yan_jump_snork_0011"
}

-- define smart terrains
smart_terrains["test1"] = {
"yan_tonnel_snorks"
}

-----------------------------------------------------------------------------------------
-- TEST 2
-----------------------------------------------------------------------------------------
-- Controller Test
object_list["test2"] = {
"yantar_stalker_zombied_0000",
"yantar_stalker_zombied_0001",
"yantar_stalker_zombied_0002",
"yantar_stalker_zombied_0005",
"yantar_stalker_zombied_0007",
"yantar_stalker_zombied_0008",
"yantar_stalker_zombied_0015",
"yantar_stalker_zombied_0043",
"yantar_stalker_zombied_0046",
"yantar_dead_scientist_01",
"yantar_dead_scientist_02",
"yantar_gulag_zombies_03",
"yantar_gulag_zombies_01",
"yantar_gulag_zombies_05",
"yantar_stalker_zombied_0025",
"yantar_exozombied",
"yantar_stalker_zombied_0016",
"yantar_stalker_zombied_0021",
"yantar_stalker_zombied_0022",
"yantar_stalker_zombied_0032",
"yantar_stalker_zombied_0044",
"yantar_stalker_zombied_0049",
"yantar_stalker_fresh_zombied",
"yantar_stalker_fresh_zombied_0001",
"yantar_m_gigant_e",
"yan_scientist_help",
"factory_zombie_strong",
"factory_zombie_strong_0000",
"factory_zombie_strong_0002",
"factory_zombie_strong_0005",
"factory_zombie_strong_0006",
"factory_zombie_strong_0007",
"factory_zombie_strong_0008",
"factory_zombie_strong_0009",
"factory_zombie_strong_0010",
"factory_zombie_strong_0011",
"factory_zombie_strong_0013",
"factory_zombie_strong_0014",
"factory_zombie_strong_0016",
"factory_zombie_strong_0017",
"factory_zombie_strong_0018",
"factory_zombie_strong_0019",
"factory_zombie_strong_0021",
"factory_zombie_strong_0022",
"factory_zombie_strong_0023",
"factory_zombie_strong_0024",
"factory_zombie_strong_0025",
"factory_zombie_strong_0026",
"factory_zombie_strong_0027",
"factory_zombie_strong_0028",
"factory_zombie_strong_0029",
"factory_zombie_strong_0030",
"factory_zombie_strong_0031",
"factory_zombie_strong_0032",
"factory_zombie_normal",
"factory_zombie_weak",
"factory_zombie_weak_0000",
"factory_zombie_weak_0001",
"factory_zombie_weak_0002",
"factory_zombie_weak_0003",
"factory_zombie_weak_0004",
"factory_zombie_weak_0005",
"factory_zombie_weak_0006",
"factory_zombie_weak_0007",
"factory_zombie_weak_0008",
"factory_zombie_strong_0001",
"factory_zombie_strong_0003",
"factory_zombie_strong_0004",
"factory_zombie_strong_0012",
"factory_zombie_strong_0015",
"factory_zombie_strong_0020",
"factory_zombie_strong_0033",
"factory_zombie_strong_0034",
"factory_zombie_strong_0035",
"factory_zombie_strong_0036",
"factory_zombie_strong_0037",
"factory_zombie_strong_0038",
"factory_zombie_strong_0039",
"factory_zombie_strong_0040",
"factory_zombie_strong_0041",
"factory_zombie_strong_0042",
"yantar_ecolog_general",
"yantar_klyk",
"yantar_ghost"
}

smart_terrains["test2"] = {
"yantar_zombies",
"yan_scientist"
}

------------------------------------------------------------------------------
-- Base Run function (load extern)
------------------------------------------------------------------------------
function r(index)
	test_utils.setup_test(object_list, smart_terrains)
	test_utils.run_test(index)
end
