function main ()

lvl_red_forest_return_2.main()

local infos_table = {
"red_bridge_actor_come",
"red_bridge_actor_in_position",
"red_bridge_down_done",
"red_bridge_finished"
}
local actor = db.actor

for k,v in pairs(infos_table) do
	actor:give_info_portion(v)
end

if level.name() == "limansk" and not task_manager.get_task_manager().inited_tasks["csky_general_lim_go_into_limansk"] then
	xr_effects.give_inited_task(nil, nil, {"storyline", "lim_go_into_limansk", "csky"})
end

end
