function main ()

lvl_agroprom_start.main()

local infos_table = {
"agr_actor_inside_1",
"agr_actor_inside_2",
"agr_actor_inside_3",
"agr_actor_inside_4",
"agr_actor_inside_5",
"agr_actor_inside_6",
"agr_actor_inside_7",
"agr_actor_inside_8",
"agr_actor_inside_9"
}
local actor = db.actor

for k,v in pairs(infos_table) do
	actor:give_info_portion(v)
end

--if level.name() == "agroprom_underground" then
--	xr_effects.give_inited_task(nil, nil, {"storyline", "", ""})
--end
	
end
